name: CI
on:
  push:
     branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-14]
        java: [ '17', '21', '25' ]
    name: Test using Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
    - uses: sbt/setup-sbt@v1
    - run: sbt +test
