name: CI
on:
  push:
     branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    name: Test using Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
    - run: sbt +test
