name: CI
on:
  push:
     branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        java: [ '17', '21' ]
    name: Test using Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
    - uses: sbt/setup-sbt@v1
    - run: sbt +test
